version: 1.1.{build}

branches:
  only:
  - master
  
image: Visual Studio 2017
  
init:
  - git config --global core.autocrlf true
  
before_build:
 - cmd: dotnet restore TagHelperSamples\TagHelperSamples.sln

build_script:
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Bootstrap
 - cmd: dotnet pack TagHelperSamples\src\TagHelperSamples.Bootstrap
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Markdown
 - cmd: dotnet pack TagHelperSamples\src\TagHelperSamples.Markdown
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Markdown.Tests
 - cmd: dotnet publish TagHelperSamples\src\TagHelperSamples.Web
 
test_script:
 - ps: cd .\TagHelperSamples\src\TagHelperSamples.Markdown.Tests
 - cmd: dotnet test  
 
artifacts:
 - path: '\TagHelperSamples\src\TagHelperSamples.Web\bin\Debug\netcoreapp1.0\publish'
   name: WebSite
   type: WebDeployPackage   
 - path: '**\*.nupkg' 
   type: 'NuGetPackage'

deploy:
- provider: Environment
  name: TagHelperSamples-Production
